import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const getTime = async () => {
  const response = await fetch('http://worldtimeapi.org/api/timezone/Europe/Copenhagen', {
    next: {
      tags: ['time'],
    },
  });
  const data = await response.json();
  return data.datetime as string;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const time = await getTime();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1>Current time in Copenhagen</h1>
          <p>{time}</p>
        </div>
        {children}</body>
    </html>
  );
}
